# Sidebar navigation

- label: Back to Main Page
  link: https://rdu.im
- label: Linux
  items:
    - label: 'Command'
      link: '/tech-notes/linux/command'
    - label: 'CAN Bus'
      link: '/tech-notes/linux/canbus'
    - label: 'Wireguard'
      link: '/tech-notes/linux/wireguard'
    - label: 'Raspberry Pi'
      link: '/tech-notes/linux/raspberrypi'
    - label: 'BeagleBone'
      link: '/tech-notes/linux/beaglebone'
- label: Coding
  items:
    - label: 'GDB'
      link: '/tech-notes/coding/gdb'
    - label: 'Valgrind'
      link: '/tech-notes/coding/valgrind'
    - label: 'Endianness'
      link: '/tech-notes/coding/endianness'
- label: Robotics
  items:
    - label: 'Control'
      link: '/tech-notes/robotics/control'
    - label: 'Planning'
      link: '/tech-notes/robotics/planning'
    - label: 'Simulation'
      link: '/tech-notes/robotics/simulation'
    - label: 'Visualization'
      link: '/tech-notes/robotics/visual'
    - label: 'Book List'
      link: '/tech-notes/robotics/refbook'
- label: HOWTOs
  items:
    - label: 'Create SSH Key'
      link: '/tech-notes/howto/create-ssh-key'
    - label: 'Recover STM32 SWD'
      link: '/tech-notes/howto/recover-stm32-swd'
    - label: 'Xbox Linux Bluetooth'
      link: '/tech-notes/howto/xbox-controller-ubuntu-bluetooth'
- label: Resource
  items:
    - label: 'Tutorial'
      link: '/collection/resource/tutorial'
    - label: 'Course'
      link: '/collection/resource/course'
    - label: 'Tech Blog'
      link: '/collection/misc/blog'
    - label: 'Software'
      link: '/collection/resource/software'
    - label: 'Reference'
      link: '/collection/resource/reference'
# - label: Miscellaneous
#   items:
#     - label: 'Tech Blogs'
#       link: '/collection/misc/blog'
    # - label: 'Graduate Research'
    #   link: '/collection/misc/gradguide'