# Sidebar navigation

- label: Back to Main Page
  link: https://rdu.im
- label: System
  items:
    - label: 'Software'
      link: '/tech-notes/system/software'
    - label: 'Hardware'
      link: '/tech-notes/system/hardware'
    # - label: 'Application'
    #   link: '/tech-notes/system/application'
- label: Program
  items:
    - label: 'C++'
      link: '/tech-notes/program/cpp'
    - label: 'Python'
      link: '/tech-notes/program/python'
    - label: 'Tool'
      link: '/tech-notes/program/tools'
    - label: 'Library'
      link: '/tech-notes/program/library'
- label: Robotics
  items:
    - label: 'Sensing'
      link: '/tech-notes/robotics/sensing'
    - label: 'Planning'
      link: '/tech-notes/robotics/planning'
    - label: 'Control'
      link: '/tech-notes/robotics/control'
    - label: 'Simulation'
      link: '/tech-notes/robotics/simulation'
    - label: 'Reference'
      link: '/tech-notes/robotics/reference'
- label: HOWTOs
  items:
    - label: 'HOWTO List'
      link: '/tech-notes/howto/howto-list'
- label: Resource
  items:
    - label: 'Tutorial'
      link: '/collection/resource/tutorial'
    - label: 'Course'
      link: '/collection/resource/course'
    - label: 'Tech Blog'
      link: '/collection/misc/blog'
    # - label: 'Reference'
    #   link: '/collection/resource/reference'
# - label: Miscellaneous
#   items:
#     - label: 'Tech Blogs'
#       link: '/collection/misc/blog'
    # - label: 'Graduate Research'
    #   link: '/collection/misc/gradguide'